Import Debian changes 1:1.02-7njl.1
nullmailer (1:1.02-7njl.1) sarge-backports; urgency=low
.
  * Backport to Sarge.
  * Remove /usr/lib/sendmail and mail-transport-agent so this package
    can install alongside a real MTA.
  * Allow null envelope-sender.
  * Send QUIT before disconnecting, to reduce log noise from MTAs that do
    care about strict RFC2821 (reverts an early upstream change).
  * Remove IPv6 patch as it needs AI_NUMERICSERV and I haven't time to fix it.
.
nullmailer (1:1.02-8) unstable; urgency=low
.
  * Fixed links to manpages. (closes: #373104)
  * Readded autoconf and automake1.9 build-depencencies to fix IPv6 support
    again. (closes: #369743)
  * Added patch from Marc Herbert to fix autoconf/automake madness.
    (closes: #373267)
  * Removed ucf handling from postinst. (closes: #369568)
  * Updated french debconf translation from Philippe Batailler.
    (closes: #366750)
.
nullmailer (1:1.02-7) unstable; urgency=low
.
  * Updated french debconf translation from Philippe Batailler.
    (closes: #366750)
  * Added a new patch to use EHLO instead HELO when using SMTP AUTH.
    (closes: #366685)
  * Removed outdated informations about backports from README.Debian.
.
nullmailer (1:1.02-6) unstable; urgency=low
.
  * Launch debconf-updatepo in debian/rules. (closes: #366686)
.
nullmailer (1:1.02-5) unstable; urgency=medium
.
  * Preserve administrator settings when debconf is used. (closes: #366296)
.
nullmailer (1:1.02-4) unstable; urgency=low
.
  * Updated Standards-Version to 3.7.2.0, no changes required.
  * Really added support for smtp auth via debconf (got lost in -3).
.
nullmailer (1:1.02-3) unstable; urgency=low
.
  * Complete rewrite of build-sytem:
    + Switched to debhelper and dpatch.
    + Added support for smtp auth via debconf. (closes: #349485)
    + Removed ucf support. (closes: #311621, #333313)
.
nullmailer (1:1.02-2) unstable; urgency=low
.
  * Fixed 05syslog.diff so successfully sent mails are no longer logged as
    failures. (closes: #351021)

diff --git a/debian/patches/03_syslog.diff b/debian/patches/03_syslog.diff
--- a/debian/patches/03_syslog.diff
+++ b/debian/patches/03_syslog.diff
@@ -1,6 +1,22 @@
+#! /bin/sh -e
+if [ $# -ne 1 ]; then 
+    echo >&2 "`basename $0`: script expects -patch|-unpatch as argument"
+    exit 1  
+fi
+case "$1" in 
+    -patch) patch -f --no-backup-if-mismatch -p1 < $0;;
+    -unpatch) patch -f --no-backup-if-mismatch -R -p1 < $0;;
+    *)
+        echo >&2 "`basename $0`: script expects -patch|-unpatch as argument"
+        exit 1;;
+esac
+
+exit 0
+
+@DPATCH@
 diff -Nur nullmailer-1.02.orig/doc/nullmailer-send.8 nullmailer-1.02/doc/nullmailer-send.8
---- nullmailer-1.02.orig/doc/nullmailer-send.8	2006-01-21 19:42:26.000000000 +0000
-+++ nullmailer-1.02/doc/nullmailer-send.8	2006-01-21 19:42:58.000000000 +0000
+--- nullmailer-1.02.orig/doc/nullmailer-send.8	2006-03-30 16:08:37.000000000 +0000
++++ nullmailer-1.02/doc/nullmailer-send.8	2006-03-30 16:08:55.000000000 +0000
 @@ -3,6 +3,7 @@
  nullmailer-send \- Send queued messages
  .SH SYNOPSIS
@@ -27,7 +43,7 @@ diff -Nur nullmailer-1.02.orig/doc/nullmailer-send.8 nullmailer-1.02/doc/nullmai
  .TP
 diff -Nur nullmailer-1.02.orig/protocols/protocol.cc nullmailer-1.02/protocols/protocol.cc
 --- nullmailer-1.02.orig/protocols/protocol.cc	2005-11-10 16:11:12.000000000 +0000
-+++ nullmailer-1.02/protocols/protocol.cc	2006-01-21 19:45:32.000000000 +0000
++++ nullmailer-1.02/protocols/protocol.cc	2006-03-30 16:10:03.000000000 +0000
 @@ -22,11 +22,15 @@
  #include <config.h>
  #include <stdio.h>
@@ -44,7 +60,7 @@ diff -Nur nullmailer-1.02.orig/protocols/protocol.cc nullmailer-1.02/protocols/p
  const char* user = 0;
  const char* pass = 0;
  const char* cli_help_suffix = "";
-@@ -40,6 +44,8 @@
+@@ -40,23 +44,35 @@
      "Set the user name for authentication", 0 },
    { 0, "pass", cli_option::string, 0, &pass,
      "Set the password for authentication", 0 },
@@ -53,12 +69,19 @@ diff -Nur nullmailer-1.02.orig/protocols/protocol.cc nullmailer-1.02/protocols/p
    {0, 0, cli_option::flag, 0, 0, 0, 0}
  };
  
-@@ -51,12 +57,19 @@
+ void protocol_fail(int e, const char* msg)
+ {
++  if (use_syslog)                                                                                                                                            
++    syslog(LOG_ERR, "%s: Failed: %s", cli_program, msg);                                                                                                     
++  if (!daemonize)                                                                                                                                            
+   ferr << cli_program << ": Failed: " << msg << endl;
+   exit(e);
+ }
  
  void protocol_succ(const char* msg)
  {
 +  if (use_syslog)
-+    syslog(LOG_ERR, "%s: Failed: %s", cli_program, msg);
++    syslog(LOG_ERR, "%s: Succeeded: %s", cli_program, msg);
 +  if (!daemonize)
    ferr << cli_program << ": Succeeded: " << msg << endl;
    exit(0);
@@ -75,7 +98,7 @@ diff -Nur nullmailer-1.02.orig/protocols/protocol.cc nullmailer-1.02/protocols/p
    protocol_prep(&in);
 diff -Nur nullmailer-1.02.orig/src/Makefile.in nullmailer-1.02/src/Makefile.in
 --- nullmailer-1.02.orig/src/Makefile.in	2005-12-07 22:35:01.000000000 +0000
-+++ nullmailer-1.02/src/Makefile.in	2006-01-21 19:42:58.000000000 +0000
++++ nullmailer-1.02/src/Makefile.in	2006-03-30 16:08:55.000000000 +0000
 @@ -63,7 +63,7 @@
  nullmailer_queue_DEPENDENCIES = ../lib/libnullmailer.a
  am_nullmailer_send_OBJECTS = send.$(OBJEXT)
@@ -103,7 +126,7 @@ diff -Nur nullmailer-1.02.orig/src/Makefile.in nullmailer-1.02/src/Makefile.in
  all: all-am
 diff -Nur nullmailer-1.02.orig/src/send.cc nullmailer-1.02/src/send.cc
 --- nullmailer-1.02.orig/src/send.cc	2005-11-10 16:11:12.000000000 +0000
-+++ nullmailer-1.02/src/send.cc	2006-01-21 19:42:58.000000000 +0000
++++ nullmailer-1.02/src/send.cc	2006-03-30 16:08:55.000000000 +0000
 @@ -27,6 +27,7 @@
  #include <stdlib.h>
  #include <string.h>
